path: "/content/gdrive/My Drive/Projects/Object Detection/Yolo v8/dataset"     # dataset root directory
train: "train/images"        # train images (relative to 'path')
val: "val/images"       # validation images (relative to 'path')   
test: "test/images"     # test images (relative to 'path') 

# Classes
names:
  0: cheetah
# 1: <class2-name>
# 2: <class3-name>
# 3: <class4-name>
